import { DOC_TYPES } from './doc-types.mjs';

export const OKF_RESERVED_FIELDS = new Set([
  'type',
  'title',
  'description',
  'resource',
  'tags',
  'timestamp',
  'arckit',
]);

export const OKF_DEFAULT_TAGS = ['arckit'];

function slugTag(value) {
  return String(value || '')
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

export function okfTypeForDocType(docType, meta = DOC_TYPES[docType]) {
  if (meta?.name) return meta.name;
  if (docType) return `ArcKit ${docType} Artifact`;
  return 'ArcKit Artifact';
}

export function okfTagsForDocType(docType, meta = DOC_TYPES[docType]) {
  const tags = new Set(OKF_DEFAULT_TAGS);
  if (docType) tags.add(slugTag(docType));
  if (meta?.category) tags.add(slugTag(meta.category));
  if (meta?.regime) tags.add(slugTag(meta.regime));
  if (meta?.severity) tags.add(slugTag(`${meta.severity}-severity`));
  return Array.from(tags).filter(Boolean);
}

export function okfDescriptionForDocument({ title, documentId, category } = {}) {
  const subject = title || documentId || 'ArcKit artifact';
  const suffix = documentId ? ` (${documentId})` : '';
  const categoryText = category ? ` in the ${category} category` : '';
  return `${subject}${suffix} generated by ArcKit${categoryText}.`;
}

